name: Build on Raspberry Pi
on:
  push:
    paths:
      - "include/**"
      - "src/**"
      - "Makefile"
      - "gh-actions-rpi-cmd.sh"
      - "install-deps.sh"
  workflow_dispatch:

jobs:

  build:

    name: Build on ${{ matrix.cpu }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: ["raspios_lite:2021-05-07"]
        cpu: [arm1176, cortex-a8]

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Build RPI environment
      uses: pguyot/arm-runner-action@v1
      with:
        commands: ./gh-actions-rpi-cmd.sh
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 10000
        cpu: ${{ matrix.cpu }}
        optimize_image: false

  notify_hx711-rpi-py:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    needs: [build]
    steps:
      - name: Send HTTP request
        run: |
          curl -XPOST -u "${{ secrets.HX711_RPI_PY_USERNAME }}:${{ secrets.HX711_RPI_PY_PAT }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/endail/hx711-rpi-py/dispatches --data '{"event_type":"build"}'
