name: Build Status
on: ["push"]

jobs:
  build:
    name: buildcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test make and install
        run: make all && sudo make install
