name: Build Status
on: ["push"]

jobs:
  build:
    name: buildcheck
    runs-on: ubuntu-latest
    steps:

      - name: Build and Install lgpio
        run: |
          wget https://abyz.me.uk/lg/lg.zip
          unzip lg.zip
          cd lg
          make
          sudo make install
          sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
          sudo ldconfig
          sudo chown -R $USER:$USER /home/runner/work

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test make and install
        run: make all && sudo make install
