name: cppcheck
on: ["push"]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:

      - name: Clone lgpio
        uses: actions/checkout@v2
        with:
          repository: 'joan2937/lg'

      - name: Build and Install lgpio
        run: |
          sudo apt install swig python-dev python3-dev
          sudo apt install python-setuptools python3-setuptools
          make
          sudo make install
          sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
          sudo ldconfig
          sudo chown -R $USER:$USER /home/runner/work

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
        
      - name: Publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: change-to-lgpio
