name: cppcheck
on:
  push:
    paths:
      - "include/**"
      - "src/**"
      - "Makefile"
      - "gh-actions-rpi-cmd.sh"
      - "install-deps.sh"

jobs:

  build:

    name: Build on ${{ matrix.cpu }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: ["raspios_lite:latest"]
        cpu: [arm1176, cortex-a8]

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    
    - name: Build RPI environment
      uses: pguyot/arm-runner-action@v2
      with:
        commands: ./gh-actions-rpi-cmd.sh
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 10000
        cpu: ${{ matrix.cpu }}
        optimize_image: false

    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        inline_suppression: enable
        platform: unix32
        std: c++11
        other_options: --suppress=unusedFunction --suppress=missingIncludeSystem
        output_file: resources/cppcheck_report.txt

    - name: Publish report    
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: master
